language: node_js
node_js:
- 8.3.0
cache:
  directories:
  - node_modules
addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN
branches:
  only:
  - master
script: npm test -- --coverage --ci --runInBand
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
env:
  global:
  # CODE_CLIMATE_TOKEN
  - secure: cVTAEcebNjiExqT6Bj21qUUJHBmMcVny8Cfk11+HwsVBmRVYefE0Jd8RKLLt0ktiiYiAeP98yn3ZGe0QYrw2j4xz1ahZhSD3mk48yaK+dmYdvWUj25ABA+4wBey1mA/Y6+x3e6nnmB5sS2qYpju8F8+BORefOKZZ7z8ksXHjzeLc+Rw85VXrgdrq3mhAOh7RIKV6XtdFcVx7YDLJLo5fdEEt8/DQPif1Z8+JwuIEBmpm+qLamuzOafUNaWscAfMDS4do8iHwTIq8OkxVPSHCWYdPAEv0bnV9+mnrotD3b/S0zSJbTKj2xuTKMUf6EQD7jJoLmtlReUwJKTCiTs5ZCw5FytOi8TFR6ARgLjO6Mmiw8gXlDwAqyw0OIZDOFbsBEb9VE6Brcti+bcadMOmqeqGGtD3IPJ5rEcVXtEWeY+6TuTdqMKdLJnjNYCpTm4KIKi+WW3GtmpOS4lwno2OghyPyqcoVkIgdLRGGzNoa7LW6io9Q/sGhlSEGF1+C6oNaWjhbTE8dGeOsPGT+Kfm0cOm7Sz8G6pDErU18ReewMFxzOKst8GkV/8eap9RClS4HKuPWd7KEyizWGZQp9GtEFYndcYQWsX3WfQ0Tm1YeUbT4RCMFoYiI7hhJVrNH/EfykfFKf692oPFQUJss+3n9JlVs1GFlizAERRSFoPKCvN8=
