language: node_js
node_js:
- 8.3.0
cache:
  directories:
  - node_modules
addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN
branches:
  only:
  - master
script: npm test -- --coverage --ci --runInBand
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
env:
  global:
  # CODE_CLIMATE_TOKEN
  - secure: H97/vjsmF4MxnZxubYws7b3sIsqfFXxfbCFzWxwCwJAX2XXMjepLjRDsQGXt7L+3GBraciZofs427U0xaVqJWcGsQPRX94v0Gu6X0XxkVszXn09GxqdW0BX0nIfwBI7emVDOgXuAKiG/YNHaNc8LpF7tBmcm0lm0mCxi+TcJSZuqZjAQK/RcmCcheUYkiPN5F3Cg+JyTma52em80IWHyd+WaKq4ty5FCYtj1hqoHuNC/4DtnwEkiU2a5xmdzmIloZCxUuGpceQOUZOsY77QpdTVYsyhlzU53t2R1ST1Ek187iViyQJBepVpYfU73RRFHKTZXeFWqj55YjXdxRA5hU0jFzXzPQBzxHeY9Zhd9F5wQCDbpshHnpWlz1CD2MTHdE5cKgAb8lIMaCzCp0V/G+LpVwsNSrPx/y4UBpg4QuMuYGvz+QUGyzjkJKSMxcjmh7Va+sXD4gHpI+ZA/7wgUAkx/q8qKSc9S7Yd+Ih4s+2uGF4BM3V0I1C/4G4PF8XbdYbm07Pd6AMbZ3xiEmWnWaHejYEuH6mkbc3FEYl/RzrNjs7q+B/e/HvjZ60PRuqfbvxMgxROhfU8Q7FWvDge0nIjMHJW8MRlr0yCRziTETDRT5G6Gz0Ft3yuS9OF2vrVjnK7LOmyRNH7L4PhLJhyvf6ZZ5Dvi0kof0VsdnU3kCTM=
