language: node_js
node_js:
- 8.3.0
cache:
  directories:
  - node_modules
addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN
branches:
  only:
  - master
script: npm test -- --coverage --ci --runInBand
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
env:
  global:
  # CODE_CLIMATE_TOKEN
  - secure: dcjjU8ylx2M4ZdDQlB6oYOZESbyD6szlJ8GvG65qyINld63RKQkrahlyft9gem5DcVlX0RPVVhxWlE+9mVOtYCEgNIYPY5U4dW9l+lpGjVZMSt2TcbPSySxBVm9XbrDJaeC8w4a4M3GuZk2SN9hbOuWzf0eRaW6uGFFx8MdOeDzY8DuL6LfBEoRtRlwAXSMLYZZJGR7S8Dr2EsMnkVCrpAwZZsn72I+vQhI3fXymyUWKrQFH+6ySp1D70Nc/5VvbjsfrZAsH3wpcTsBHkkmCYlnUsZSgm+iHBUshd3l56tZb0VnYVyiuKSuirbaBGwFr0XetDu968eCXg+Y40eGU8jp1rveNeG1fhpuhXPGu2rdIvVbMg17R3i4aNBnChfVybeBgHWtHXoQbBLPxX8dNi5LRA6NuK3aUbZpaChGUfeZ6ZF9Mq77VO+cuNFQbKVVO5FwlKQWIiqIdIryKb1XGPMg62uZnLMDnQgTSNcTU+L7Y3cKj5008TVmkIUB4LUwTY4foY+IwH0hHpi03juMPdiaZqi7DhteHQqietvu62a7L4OhyuogQo4ulviOZFmtHpyWk+22ky88HrsrUnOR2qwuiIDwdbfjPWIDIBXgsLtEDIjwp+61y8MvppQ6g5VNJ7T+s6MKeZgrIKTSMhJnAry/AxDEOrNLReBFpQHyRsa4=
